# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_item_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wearloc',
            field=models.CharField(default='finger', max_length=16),
            preserve_default=False,
        ),
    ]
