# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0005_auto_20180428_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wearloc',
            field=models.CharField(choices=[('none', '\u043d\u0435\u0442'), ('light', '\u0441\u0432\u0435\u0442'), ('finger', '\u043f\u0430\u043b\u0435\u0446'), ('neck', '\u0448\u0435\u044f'), ('body', '\u0432\u043e\u043a\u0440\u0443\u0433 \u0442\u0435\u043b\u0430'), ('head', '\u0433\u043e\u043b\u043e\u0432\u0430'), ('legs', '\u0431\u0435\u0434\u0440\u0430'), ('feet', '\u043d\u043e\u0433\u0438'), ('hands', '\u0440\u0443\u043a\u0438'), ('arms', '\u043f\u043b\u0435\u0447\u0438'), ('shield', '\u0449\u0438\u0442'), ('about', '\u043d\u0430 \u0442\u0435\u043b\u043e'), ('waist', '\u0442\u0430\u043b\u0438\u044f'), ('wrist', '\u0437\u0430\u043f\u044f\u0441\u0442\u044c\u0435'), ('wield', '\u043e\u0440\u0443\u0436\u0438\u0435'), ('hold', '\u0432 \u0440\u0443\u043a\u0430\u0445'), ('float', '\u043a\u0440\u0443\u0436\u0438\u0442\u0441\u044f'), ('face', '\u043b\u0438\u0446\u043e'), ('ears', '\u0443\u0448\u0438'), ('horse', '\u043b\u043e\u0448\u0430\u0434\u0438\u043d\u043e\u0435 \u0442\u0435\u043b\u043e'), ('hooves', '\u043a\u043e\u043f\u044b\u0442\u0430')], default='none', max_length=16),
        ),
    ]
