# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0006_auto_20180428_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
