# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0007_item_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='stat_size',
        ),
    ]
