# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0008_auto_20180428_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='where',
            field=models.CharField(default='', max_length=256),
        ),
    ]
