# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0009_auto_20180428_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='damage',
            field=models.CharField(default='', max_length=256),
        ),
    ]
