# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0013_auto_20180429_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnum', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('weaponClass', models.CharField(choices=[('exotic', '\u044d\u043a\u0437\u043e\u0442\u0438\u043a\u0430'), ('sword', '\u043c\u0435\u0447'), ('dagger', '\u043a\u0438\u043d\u0436\u0430\u043b'), ('staff', '\u0448\u0435\u0441\u0442'), ('spear', '\u043a\u043e\u043f\u044c\u0435'), ('mace', '\u0431\u0443\u043b\u0430\u0432\u0430'), ('axe', '\u0442\u043e\u043f\u043e\u0440'), ('flail', '\u0446\u0435\u043f'), ('whip', '\u043f\u043b\u0435\u0442\u043a\u0430'), ('polearm', '\u0430\u043b\u0435\u0431\u0430\u0440\u0434\u0430'), ('bow', '\u043b\u0443\u043a'), ('arrow', '\u0441\u0442\u0440\u0435\u043b\u0430'), ('lance', '\u043f\u0438\u043a\u0430'), ('stone', '\u043a\u0430\u043c\u0435\u043d\u044c')], default='exotic', max_length=16)),
                ('special', models.CharField(max_length=100)),
                ('d1', models.IntegerField(default=0)),
                ('d2', models.IntegerField(default=0)),
                ('ave', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('dr', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('mana', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('stat_str', models.IntegerField(default=0)),
                ('stat_int', models.IntegerField(default=0)),
                ('stat_wis', models.IntegerField(default=0)),
                ('stat_dex', models.IntegerField(default=0)),
                ('stat_con', models.IntegerField(default=0)),
                ('area', models.CharField(default='', max_length=256)),
                ('where', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
