# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0015_auto_20180520_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='special',
            field=models.CharField(default='', max_length=100),
        ),
    ]
