# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0016_auto_20180520_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='wclass',
            field=models.CharField(choices=[('none', '\u043d\u0435\u0442'), ('exotic', '\u044d\u043a\u0437\u043e\u0442\u0438\u043a\u0430'), ('sword', '\u043c\u0435\u0447'), ('dagger', '\u043a\u0438\u043d\u0436\u0430\u043b'), ('staff', '\u0448\u0435\u0441\u0442'), ('spear', '\u043a\u043e\u043f\u044c\u0435'), ('mace', '\u0431\u0443\u043b\u0430\u0432\u0430'), ('axe', '\u0442\u043e\u043f\u043e\u0440'), ('flail', '\u0446\u0435\u043f'), ('whip', '\u043f\u043b\u0435\u0442\u043a\u0430'), ('polearm', '\u0430\u043b\u0435\u0431\u0430\u0440\u0434\u0430'), ('bow', '\u043b\u0443\u043a'), ('arrow', '\u0441\u0442\u0440\u0435\u043b\u0430'), ('lance', '\u043f\u0438\u043a\u0430'), ('stone', '\u043a\u0430\u043c\u0435\u043d\u044c')], default='none', max_length=16),
        ),
    ]
