# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-20 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0017_auto_20180520_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='damage',
        ),
    ]
