# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0018_remove_item_damage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnum', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('itemtype', models.CharField(choices=[('none', '\u043d\u0435\u0442'), ('potion', '\u0437\u0435\u043b\u044c\u0435'), ('pill', '\u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u043e'), ('scroll', '\u0441\u0432\u0438\u0442\u043e\u043a'), ('wand', '\u0436\u0435\u0437\u043b'), ('staff', '\u043f\u043e\u0441\u043e\u0445')], default='none', max_length=16)),
                ('spellLevel', models.IntegerField(default=0)),
                ('charges', models.IntegerField(default=0)),
                ('spells', models.CharField(default='', max_length=256)),
                ('area', models.CharField(default='', max_length=256)),
                ('where', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
