# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0019_magicitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicitem',
            name='itemtype',
            field=models.CharField(choices=[('none', '\u043d\u0435\u0442'), ('potion', '\u0437\u0435\u043b\u044c\u0435'), ('pill', '\u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u043e'), ('scroll', '\u0441\u0432\u0438\u0442\u043e\u043a'), ('wand', '\u0436\u0435\u0437\u043b'), ('staff', '\u043f\u043e\u0441\u043e\u0445'), ('spellbook', '\u043a\u043d\u0438\u0433\u0430 \u0437\u0430\u043a\u043b\u0438\u043d\u0430\u043d\u0438\u0439'), ('warp_stone', '\u0438\u0441\u043a\u0430\u0436\u0430\u044e\u0449\u0438\u0439 \u043a\u0430\u043c\u0435\u043d\u044c')], default='none', max_length=16),
        ),
    ]
