# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0020_auto_20180721_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='magicitem',
            name='limit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='weapon',
            name='limit',
            field=models.IntegerField(default=-1),
        ),
    ]
