# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0021_auto_20180721_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnum', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('act', models.CharField(default='', max_length=256)),
                ('aff', models.CharField(default='', max_length=256)),
                ('off', models.CharField(default='', max_length=256)),
                ('area', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stat_size',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='armor',
        ),
        migrations.AddField(
            model_name='item',
            name='align',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='weapon',
            name='align',
            field=models.CharField(default='', max_length=256),
        ),
    ]
