# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-12 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0022_auto_20190912_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stat_size',
            field=models.IntegerField(default=0),
        ),
    ]
